---
abstract: 'Plack Middleware to integrate with Mozilla Persona (Auth by email)'
author:
  - 'J. Bolila <bolila@cpan.org>'
build_requires:
  Dancer2: 0.10
  ExtUtils::MakeMaker: 0
  File::Spec::Functions: 0
  HTTP::Request::Common: 6.04
  List::Util: 0
  Mojo::Base: 0
  Mojo::Template: 0
  Mojolicious::Commands: 0
  Plack::Builder: 0
  Plack::Test: 0
  Test::More: 0
  lib: 0
  strict: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Auth-BrowserID
requires:
  Carp: 0
  JSON: 2.90
  LWP::Protocol::https: 6.04
  LWP::UserAgent: 6.05
  Mozilla::CA: 20130114
  Plack::Middleware: 0
  Plack::Response: 1.0029
  Plack::Session: 0.21
  Plack::Util::Accessor: 0
  parent: 0
  perl: 5.012
  warnings: 0
resources:
  bugtracker: https://github.com/jbolila/Plack-Middleware-Auth-BrowserID/issues
  repository: https://github.com/jbolila/Plack-Middleware-Auth-BrowserID
version: 0.0.1_02
